name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          base_href: "/rdr2-map/"
